pipeline {
  agent none

  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        echo 'Building Back-end...'
        sh 'mvn --version'
        sh 'mvn clean install -DskipTests'
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        echo 'Building Front-end...'
        sh 'node --version'
        sh '''
          npm install
          npm run build
        '''
      }
    }
  }
}
